server:
  port: 9000

key:
  path: https://api-keymanager.nhncloudservice.com/keymanager/v1.0/appkey/500rMJPT021TnyNl/secrets/

repository:
  id: ebd3c3842fdf44bb8ed92ab709e418d0

encrypt:
  id: 4daedecda3764a75a58614ea0d577444
  key: ${encrypt-key}

# config server
spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: git@github.com:nhnacademy-be7-55G-COM/55G.COM-config.git
          search-paths: "/"
          default-label: main
          ignore-local-ssh-settings: true
          private-key: ${config.repository.key}

---
spring:
  config:
    activate:
      on-profile: live

55g:
  log:
    path: /logs/live/config

logging:
  file:
    name: ${55g.log.path}/config-live.log
  logback:
    rollingpolicy:
      max-history: 100
      file-name-pattern: ${55g.log.path}/config-live-%d{yyyy-MM-dd}.%i.log
      max-file-size: 100KB
  level:
    root: info
    com.S5G.gateway: info

---
spring:
  config:
    activate:
      on-profile: dev

55g:
  log:
    path: /logs/dev/config

logging:
  file:
    name: ${55g.log.path}/config-dev.log
  logback:
    rollingpolicy:
      max-history: 30
      file-name-pattern: ${55g.log.path}/config-dev-%d{yyyy-MM-dd}.%i.log
      max-file-size: 100KB
  level:
    root: debug
    com.S5G.gateway: trace